// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payroll.Infrastructure.Persistence;

#nullable disable

namespace Payroll.Infrastructure.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payroll.Domain.Entities.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("ChildAllowance")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommissionOvertime")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommissionReserve")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyDeductions")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyLoanDeducted")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyLoanRemaining")
                        .HasColumnType("bigint");

                    b.Property<long?>("DailySalary")
                        .HasColumnType("bigint");

                    b.Property<long?>("DebtToCompany")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<long?>("FamilyOrFuelAllowance")
                        .HasColumnType("bigint");

                    b.Property<long?>("FundLoanDeducted")
                        .HasColumnType("bigint");

                    b.Property<long?>("FundLoanRemaining")
                        .HasColumnType("bigint");

                    b.Property<long?>("GrossReceivable")
                        .HasColumnType("bigint");

                    b.Property<long?>("HousingAllowance")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsuranceAndTaxDeductions")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsuranceWorkerShare")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LunchAllowance")
                        .HasColumnType("bigint");

                    b.Property<long?>("MissionAllowance")
                        .HasColumnType("bigint");

                    b.Property<long?>("MobileAllowance")
                        .HasColumnType("bigint");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<long?>("MonthlyBaseSalary")
                        .HasColumnType("bigint");

                    b.Property<long?>("NetPayable")
                        .HasColumnType("bigint");

                    b.Property<long?>("NetReceivable")
                        .HasColumnType("bigint");

                    b.Property<long?>("OnePerThousandInsurance")
                        .HasColumnType("bigint");

                    b.Property<long?>("OtherBenefits")
                        .HasColumnType("bigint");

                    b.Property<int?>("PaidLeaveInDays")
                        .HasColumnType("integer");

                    b.Property<long?>("ResponsibilityAllowance")
                        .HasColumnType("bigint");

                    b.Property<long?>("SalaryTax")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupplementaryInsurance")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalDeductions")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSalaryAndBenefits")
                        .HasColumnType("bigint");

                    b.Property<int?>("UnpaidLeaveInDays")
                        .HasColumnType("integer");

                    b.Property<long?>("WorkerBenefit")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorkingDays")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Payslips", "payroll");
                });
#pragma warning restore 612, 618
        }
    }
}
