// <auto-generated />
using System;
using HumanResources.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HumanResources.Infrastructure.Migrations
{
    [DbContext(typeof(HumanResourcesDbContext))]
    partial class HumanResourcesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HumanResources.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("BankNameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Iban")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BankNameId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("BankAccounts", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.BankName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BankNameList", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.ChequePromissionaryNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ChequePromissionaryNotes", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BirthPlaceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ChildrenCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("text");

                    b.Property<int?>("EmploymentTypeDisplay")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraInsurranceCount")
                        .HasColumnType("integer");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GenderDisplay")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasInsurance")
                        .HasColumnType("boolean");

                    b.Property<string>("InsurranceCode")
                        .HasColumnType("text");

                    b.Property<string>("InsurranceStatus")
                        .HasColumnType("text");

                    b.Property<string>("InternalContactNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uuid");

                    b.Property<string>("LandPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeavingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<int?>("MaritalStatusDisplay")
                        .HasColumnType("integer");

                    b.Property<string>("MostRecentDegree")
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ShenasnameIssuedPlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShenasnameNumber")
                        .HasColumnType("text");

                    b.Property<string>("ShenasnameSerial")
                        .HasColumnType("text");

                    b.Property<string>("ShenasnameSerialLetter")
                        .HasColumnType("text");

                    b.Property<string>("ShenasnameSerie")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WorkingStatusDisplay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirthPlaceId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("JobTitleId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("ShenasnameIssuedPlaceId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employees", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("JobTitles", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Provinces", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.TrackJobTitleAndLeaveHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TrackJobTitleAndLeaveHistories", "hr");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.BankName", "BankName")
                        .WithMany()
                        .HasForeignKey("BankNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Domain.Entities.Employee", "Employee")
                        .WithMany("BankAccounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankName");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.ChequePromissionaryNote", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.Employee", "Employee")
                        .WithMany("ChequePromissionaryNotes")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.City", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employee", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.City", "BirthPlace")
                        .WithMany("BirthPlaces")
                        .HasForeignKey("BirthPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Domain.Entities.JobTitle", "JobTitle")
                        .WithMany("Employees")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Domain.Entities.City", "ShenasnameIssuedPlace")
                        .WithMany("ShenasnameIssuedPlaces")
                        .HasForeignKey("ShenasnameIssuedPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Domain.Entities.Employee", "SuperVisor")
                        .WithMany("Employees")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("BirthPlace");

                    b.Navigation("JobTitle");

                    b.Navigation("ShenasnameIssuedPlace");

                    b.Navigation("SuperVisor");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.JobTitle", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.Department", "Department")
                        .WithMany("JobTitles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.TrackJobTitleAndLeaveHistory", b =>
                {
                    b.HasOne("HumanResources.Domain.Entities.Employee", "Employee")
                        .WithMany("TrackJobTitleAndLeaveHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.City", b =>
                {
                    b.Navigation("BirthPlaces");

                    b.Navigation("ShenasnameIssuedPlaces");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Department", b =>
                {
                    b.Navigation("JobTitles");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Employee", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("ChequePromissionaryNotes");

                    b.Navigation("Employees");

                    b.Navigation("TrackJobTitleAndLeaveHistories");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.JobTitle", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HumanResources.Domain.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
