// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaksunPars.Infrastructure.Data;

#nullable disable

namespace TaksunPars.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119104926_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaksunPars.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChildAllowance")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionOvertime")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionReserve")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyDeductions")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyLoanDeducted")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyLoanRemaining")
                        .HasColumnType("bigint");

                    b.Property<long>("DailySalary")
                        .HasColumnType("bigint");

                    b.Property<long>("DebtToCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("FamilyOrFuelAllowance")
                        .HasColumnType("bigint");

                    b.Property<long>("FundLoanDeducted")
                        .HasColumnType("bigint");

                    b.Property<long>("FundLoanRemaining")
                        .HasColumnType("bigint");

                    b.Property<long>("GrossReceivable")
                        .HasColumnType("bigint");

                    b.Property<long>("HousingAllowance")
                        .HasColumnType("bigint");

                    b.Property<long>("InsuranceAndTaxDeductions")
                        .HasColumnType("bigint");

                    b.Property<long>("InsuranceWorkerShare")
                        .HasColumnType("bigint");

                    b.Property<long>("LunchAllowance")
                        .HasColumnType("bigint");

                    b.Property<long>("MissionAllowance")
                        .HasColumnType("bigint");

                    b.Property<long>("MobileAllowance")
                        .HasColumnType("bigint");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<long>("MonthlyBaseSalary")
                        .HasColumnType("bigint");

                    b.Property<long>("NetPayable")
                        .HasColumnType("bigint");

                    b.Property<long>("NetReceivable")
                        .HasColumnType("bigint");

                    b.Property<long>("OnePerThousandInsurance")
                        .HasColumnType("bigint");

                    b.Property<long>("OtherBenefits")
                        .HasColumnType("bigint");

                    b.Property<int>("PaidLeaveInDays")
                        .HasColumnType("integer");

                    b.Property<string>("PersonnelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PersonnelId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResponsibilityAllowance")
                        .HasColumnType("bigint");

                    b.Property<long>("SalaryTax")
                        .HasColumnType("bigint");

                    b.Property<long>("SupplementaryInsurance")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDeductions")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSalaryAndBenefits")
                        .HasColumnType("bigint");

                    b.Property<int>("UnpaidLeaveInDays")
                        .HasColumnType("integer");

                    b.Property<long>("WorkerBenefit")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("PersonnelCode", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Payslips", (string)null);
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.Personnel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PersonnelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("PersonnelCode")
                        .IsUnique();

                    b.ToTable("Personnel", (string)null);
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PersonnelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.Payslip", b =>
                {
                    b.HasOne("TaksunPars.Core.Entities.Personnel", "Personnel")
                        .WithMany("PaySlips")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.Personnel", b =>
                {
                    b.HasOne("TaksunPars.Core.Entities.Department", "Department")
                        .WithMany("Personnels")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.User", b =>
                {
                    b.HasOne("TaksunPars.Core.Entities.Personnel", "Personnel")
                        .WithOne("User")
                        .HasForeignKey("TaksunPars.Core.Entities.User", "PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.Department", b =>
                {
                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("TaksunPars.Core.Entities.Personnel", b =>
                {
                    b.Navigation("PaySlips");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
